### ISSUE TITLE
Add move history panel

### ISSUE THREAD

**Issue by jorge1289** [jorge1289/Solomon#4]
# Overview
Add a move history display to the chess UI that shows all moves made during the game using chess.js's built-in history functionality.

# Technical Details
- The chess engine currently uses chess.js and chessboard.js libraries
- chess.js provides `history()` method that returns moves in Standard Algebraic Notation (SAN)
- Can optionally use `history({ verbose: true })` for detailed move information

# Requirements
- Display moves in a scrollable list next to the chessboard
- Show move numbers (1. e4 e5, 2. Nf3...)
- Update the display in real-time as moves are made
- (Optional) Highlight current position in the move list
- (Optional) Allow clicking on moves to jump to that position

# Suggested Implementation
1. Create a new component for move history display
2. Subscribe to move events from the chess engine
3. Use chess.js's history() method to get move data
4. Format and display moves in pairs (White/Black)

# Resources
- chess.js documentation: https://github.com/jhlywa/chess.js/blob/master/README.md
- Example of history() output: ['e4', 'e5', 'Nf3', ...]

# Definition of Done
- Move history updates correctly with each move
- Moves are displayed in standard chess notation
- UI is responsive and matches existing design
- Code follows project's style guidelines

**Comment by kesril** [comment]
Assign me this young blooderton
