### ISSUE TITLE
Implement move highlighting

### ISSUE THREAD

**Issue by jorge1289** [jorge1289/Solomon#6]
Highlight possible moves when a piece is selected

**Comment by amshunaik** [comment]
Hi, Can I try this issue.

**Comment by jorge1289** [comment]
Hi @amshunaik,
The error happens because only collaborators with write access can push directly to the main repository. For contributors without direct access, the typical workflow is:

1. Fork the repository to your own GitHub account.
2. Clone the forked repository locally.
3. Make changes and commit them to a branch in your fork.
4. Push the branch to your forked repository.
5. Create a pull request from your forked branch to the main repository.

This way, I can review your changes before merging them into the main repository. If you need any help with this process, feel free to ask!

**Comment by amshunaik** [comment]
Actuallt when I am pushing in the forked repository its showing the error 
 -> git push origin feature/move-highlighting
remote: Permission to jorge1289/Solomon.git denied to amshunaik.
fatal: unable to access 'https://github.com/jorge1289/Solomon/': The requested URL returned error: 403

**Comment by jorge1289** [comment]
Hi @amshunaik, 

Thanks for the clarification. The error happens because your `origin` remote still points to my repository (`jorge1289/Solomon.git`), where you don't have write permissions. To resolve this, please make sure your local repository is connected to your fork. Here's how you can fix it:

1. First, check the current remotes in your local repository by running:
   ```bash
   git remote -v
   ```

2. If `origin` points to `https://github.com/jorge1289/Solomon.git`, update it to your fork:
   ```bash
   git remote set-url origin https://github.com/<your-username>/Solomon.git
   ```

   Replace `<your-username>` with your GitHub username.

3. Now, try pushing your branch again:
   ```bash
   git push origin feature/move-highlighting
   ```
This should push the branch to your forked repository. Once done, you can create a pull request to propose your changes to the main repository.

**Comment by amshunaik** [comment]
So here after 2nd step when I am pushing its showing repository not found 

PS C:\Users\RAmsh\OneDrive\Desktop\OpenSource\Solomon> git push origin feature/move-highlighting
remote: Repository not found.
fatal: repository 'https://github.com/amshunaik/Solomon.git/' not found

**Comment by jorge1289** [comment]
Hi @amshunaik,

It seems like your forked repository isn’t set up correctly or isn’t named `Solomon`. Let’s verify a few things:

1. **Ensure the repository is forked**:  
   Check if you have successfully forked my repository (`jorge1289/Solomon`). You should see the fork under your GitHub account at:  
   `https://github.com/<your-username>/Solomon`  
   If you haven’t forked it yet, please do so from this link:  
   [[Fork the repository](https://github.com/jorge1289/Solomon/fork)](https://github.com/jorge1289/Solomon/fork).

2. **Check the fork’s name**:  
   If your forked repository has a different name (e.g., `Solomon-fork` instead of `Solomon`), you need to use the correct URL when setting the remote. Update your remote URL to match the actual repository name:  
   ```bash
   git remote set-url origin https://github.com/<your-username>/<repository-name>.git
   ```

3. **Verify your fork is public**:  
   If your fork is private, ensure you have the necessary permissions or make it public temporarily to push your changes.

4. **Push again**:  
   After verifying and correcting the remote URL, push your branch again:
   ```bash
   git push origin feature/move-highlighting
   ```

If the issue persists, feel free to share the error message or let me know—I’ll help you troubleshoot further!

**Comment by amshunaik** [comment]
Made pull request.

**Comment by amshunaik** [comment]
Thanks for helping out

**Comment by jorge1289** [comment]
issue done:
commit link: https://github.com/jorge1289/Solomon/commit/dadb4e8e7ffae38de9a7e2e01dee1b1e1eabf98f
